price = float(input('Цена (₽): '))
discount = float(input('Скидка (%): '))
vat = float(input('НДС (%): '))
base = round (price * (1 - discount/100),2)
vat_amount = round (base * (vat/100),2)
total =round ( base + vat_amount  ,2)
print('База после скидки:',base)
print('НДС:',vat_amount)
print('Итого к оплате:',total)
